server:
  port: 9090
#  servlet:
#    application-display-name: corporate-banking
#    context-path: /corporate-banking

spring:
  datasource:
    username: postgres
    password: 112358
    url: jdbc:postgresql://localhost/mockito
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    open-in-view: false

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql